#  Licensed under the Apache License, Version 2.0 (the "License"); you may
#  not use this file except in compliance with the License. You may obtain
#  a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#  License for the specific language governing permissions and limitations
#  under the License.

Format: 1.0
Type: Application
FullName: com.example.docker.DockerELK
Name: Docker ELK
Description: Elasticsearch, Logstash, Kibana
Author: 'Mirantis, Inc'
Tags: [docker, application, ELK]
Classes:
 com.example.docker.DockerELK: DockerELK.yaml
Require:
  com.mirantis.docker.DockerStandaloneHost:
  com.mirantis.docker.kubernetes.KubernetesPod:
  com.mirantis.docker.Interfaces:
