Namespaces:
  =: org.openstack.ci_cd_pipeline_murano_app.v2
  std: io.murano
  res: io.murano.resources
  sys: io.murano.system
  cicd: org.openstack.ci_cd_pipeline_murano_app
  puppet: org.openstack.ci_cd_pipeline_murano_app.puppet
  net: org.openstack.ci_cd_pipeline_murano_app.utils.net
  conf: io.murano.configuration

Name: CiCdEnvironment

Extends: std:Application

Properties:
  server:
    Contract: $.class(puppet:PuppetInstance)
    Usage: InOut
  clients:
    Contract:
      - $.class(puppet:PuppetClient)
    Usage: InOut

  name:
    Contract: $.string().notNull()
    Default: 'CICD2'

  puppetfileLink:
    Contract: $.string().notNull()
    Default: 'https://raw.githubusercontent.com/akhivin/cicd-dependencies/master/Puppetfile'

  master:
    Contract: $.class(puppet:PuppetServer)
    Usage: InOut

  clientsDict:
    Contract: {}
    Usage: InOut

#  manifest:
#    Contract: $.string().notNull()

Methods:
  .init:
    Body:
      - $._environment: $.find(std:Environment).require()

  deploy:
    Body:
      - $._environment.reporter.report($this, 'Using Puppetfile to install dependencies={0}'.format($this.puppetfileLink))
      - $nodes:
        - review
        - jenkins
        - openldap

      - $._environment.reporter.report($this, 'Nodes list={0}'.format($nodes))

      - $rules:
        - FromPort: 1
          ToPort: 65535
          IpProtocol: tcp
          External: false
        - FromPort: 1
          ToPort: 65535
          IpProtocol: tcp
          External: true

      - $this._environment.securityGroupManager.addGroupIngress(rules => $rules)

      - Parallel:
        - If: $.server = null
          Then:
            - $this.server: new(puppet:PuppetInstance, $this._environment,
                name => 'master',
                flavor => 'm1.medium',
                image => 'ubuntu-14.04-m-agent.qcow2',
                keyname => 'common',
                availabilityZone => 'nova',
                assignFloatingIp => true)
            - $this.server.deploy()

        - If: len($this.clients) = 0
          Then:
            - $this.clients: $nodes.select(
                new( 'org.openstack.ci_cd_pipeline_murano_app.puppet.PuppetClient', $this._environment,
                  instance => new( 'org.openstack.ci_cd_pipeline_murano_app.puppet.PuppetInstance', $this._environment,
                    name => concat('puppet_', $),
                    flavor => 'm1.medium',
                    image => 'ubuntu-14.04-m-agent.qcow2',
                    keyname => 'common',
                    availabilityZone => 'nova',
                    assignFloatingIp => true),
                  role => $))

            - $this.clients.pselect($.instance.deploy())

        - $this.clientsDict: dict($this.clients.select([$.role, $]))

      - $mainManifestPath: '/etc/puppet/environments/production/manifests/site.pp'

      - $this.master: new( puppet:PuppetServer,
          masterInstance => $this.server,
          environment => $this._environment,
          manifest => $mainManifestPath)

      # add every node with the role assigned to it
      - $this.clients.pselect(
          $this.master.addClient($))

      - $this.master.configure()

      - $gerritConfigurator: new(GerritConfigurator)
      - $gerritConfigurator.configure($this.master.masterInstance)

      - $._environment.reporter.report($this, 'Configure jenkins')

      - $jenkinsConfigurator: new(JenkinsConfigurator)
      - $jenkinsConfigurator.configure($this.master.masterInstance)

      - $ldapConfigurator: new(LdapConfigurator)
      - $ldapConfigurator.configure($this.master.masterInstance)

      - $this._environment.reporter.report($this, 'Installing dependencies')

      - $this.master.installDependencies(
          environment => 'production',
          puppetfileLink => $this.puppetfileLink)

      - $resources: new(sys:Resources)
      - $mainManifestContent: $resources.string('scripts/site.pp')
      - new(conf:Linux).putFile(
          $this.server.agent,
          $mainManifestContent,
          $mainManifestPath)

      - $this.applyManifests()

  applyManifests:
    Usage: Action
    Body:
      - $this.master.runPuppetAgents()
      - $this.printInfo()

  printInfo:
    Usage: Action
    Body:
      # Info should be printed by single instruction
      # to avoid rows mixing at output
      - $rows: list('--------------- Application info start ---------------', 'Dependencies={0}'.format($this.puppetfileLink))
      - $rows: $rows + $this.clients.pselect('{0} can be accessed on {1}'.format($.role, $.instance.floatingIpAddress))
      - $rows: $rows.append('--------------- Application info end -----------------')
      - $._environment.reporter.report($this, $rows.join('\n'))
